config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :events
  end
  resources :events
  resources :sessions, only: %i[create new destroy]
  root to: 'users#index'
  get '/signup', to: 'users#new'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :body, :date, :user_id

  belongs_to :user

  has_many :invites
  has_many :attendees, through: :invites, source: :user

  scope :upcoming_date, -> { select { |event| event.date >= Time.zone.now } }
  scope :past_date, -> { select { |event| event.date < Time.zone.now } }

  def self.creator(event)
    User.where(id: event.user_id).first
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  validates_presence_of :name

  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  has_many :events

  has_many :invites
  has_many :attended_events, through: :invites, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :login_required, except: [:index]

  # This method checks if we have a user signed in
  def login_required
    unless logged_in?
      flash[:alert] = 'You need to login first!'
      redirect_to new_session_path
    end
  end

  def logged_in?
    !!current_user
  end

  helper_method :logged_in?

  # This method gives us details about our user
  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      false
    end
  end

  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_required, only: %i[new create]
  def show
    @event = Event.find(params[:id])
    @event_creator = Event.creator(@event)
  end

  def index
    @events = Event.all.limit(10)
    @upcoming_events = @events.upcoming_date
    @past_events = @events.past_date
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to user_path(current_user.id)
    else
      redirect_to new_events_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :body, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user = User.where(name: params[:name]).first
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = 'Invalid name!'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def login(_user)
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required

  def index
    @user = current_user ? current_user.name : 'Guest'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.where(name: @user.name).empty?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Name exists! Please select a different name.'
      redirect_to signup_path
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      @created_events = @user.events
      @user_past_events = @created_events.past_date
      @user_upcoming_events = @created_events.upcoming_date
      @user_invites = @user.invites
    else
      flash[:alert] = 'User does not exist!'
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_action
    if current_user
      concat(content_tag(:li) do
        link_to 'Profile', user_path(current_user)
      end)
      concat(content_tag(:li) do
        link_to 'Create Event', new_event_path
      end)
      content_tag(:li) do
        link_to 'Logout', logout_path
      end
    else
      concat(content_tag(:li) do
        link_to 'Login', login_path
      end)
      content_tag(:li) do
        link_to 'Sign Up', signup_path
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def past_events_action
    if @past_events.size.positive?
      @past_events.map { |event| link_to event.name, event_path(event.id) }.join.html_safe
    else
      content_tag(:p) do
        'No past events found!'
      end
    end
  end

  def upcoming_events_action
    if @upcoming_events.size.positive?
      @upcoming_events.map { |event| link_to event.name, event_path(event.id) }.join.html_safe
    else
      content_tag(:p) do
        'No upcoming! events found!'
      end
    end
  end

  def attendees_action
    @event.attendees.map { |i| link_to i.name, user_path(i.id) }.join.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_invites_action
    @user_invites.map { |invite| link_to Event.where(id: invite.event_id).first.name, event_path(invite.event_id) }.join.html_safe
  end

  def user_past_events_action
    if @user_past_events.size.positive?
      @user_past_events.map { |event| link_to event.name, event_path(event.id) }.join.html_safe
    else
      content_tag(:p) do
        'No past events found!'
      end
    end
  end

  def user_upcoming_events_action
    if @user_upcoming_events.size.positive?
      @user_upcoming_events.map { |event| link_to event.name, event_path(event.id) }.join.html_safe
    else
      content_tag(:p) do
        'No upcoming! events found!'
      end
    end
  end
end

app/views/events/index.html.erb
<h1 class="title">All Events!</h1>
<h3>Past Events:</h3>
<br>
<%= past_events_action %>
<br>
<h3>Upcoming Events:</h3>
<br>
<%= upcoming_events_action %>

app/views/events/new.html.erb
<h1>Create a new event:</h1>
<%= form_for @event do |e| %>
<%= e.label :name %>
<%= e.text_field :name %><br>
Enter Event Body: <%= e.text_field :body %><br>
Enter Event Date: <%= e.datetime_field :date %><br>
<%= e.submit %>
<% end %>

app/views/events/show.html.erb
<h1 class="title"><%= @event.name %></h1>
<p><strong>Created by: <%= @event_creator.name %></strong></p>
<p> <%= @event.body%> </p>
<br>
<h3>Attendees:</h3>
<%= attendees_action %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul class = "navbar">
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "Events", events_path %></li>
         <%= menu_action %>
        </ul>
      </nav>
    </header>
    <% flash.each do |type,  msg| %>
      <p style="color: red"><%= msg %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="title">Welcome to Private Events <span><%= @user %></span></h1>

app/views/users/new.html.erb
<%= form_for @user do |user| %>
<%= user.text_field :name %>
<%= user.submit %>
<% end %>

app/views/users/show.html.erb
<h1 class="title"><%= @user.name %>'s Profile</h1>
<br>
<h3>Invitations:</h3>
<ul class = "list-nav">
  <%= user_invites_action %>
</ul>
<br>
<h3>Past Events:</h3>
<%= user_past_events_action %>
<br>
<h3>Upcoming Events:</h3>
<%= user_upcoming_events_action %>